<?xml version="1.0"?>
<robot name="box" xmlns:xacro="http://wiki.ros.org/xacro">

  <xacro:macro name="box"
               params="prefix='box_' connected_to:='' xyz:='0 0 0' rpy:='0 0 0' height:=0.15 width:=0.5 depth=0.5">

    <xacro:property name="wall_thickness" value="0.02"/>
    <xacro:property name="PI" value="3.1415926"/>
    <xacro:property name="leg_radius" value="0.02"/>
    <xacro:property name="leg_length" value="${height - table_top_thickness}"/>

    <material name="grey">
      <color rgba="0.7 0.7 0.7 1"/>
    </material>

    <xacro:if value="${connected_to == ''}">
      <link name="world"/>
      <xacro:property name="base_frame_name" value="world"/>
    </xacro:if>
    <xacro:unless value="${connected_to == ''}">
      <xacro:property name="base_frame_name" value="${connected_to}"/>
    </xacro:unless>
    <link name="${base_frame_name}"/>
    <joint name="${prefix}base_to_${base_frame_name}" type="fixed">
      <parent link="${base_frame_name}"/>
      <child link="${prefix}base_link"/>
      <origin rpy="${rpy}" xyz="${xyz}"/>
    </joint>

    <link name="${prefix}base_link"/>
    <joint name="base_to_bottom" type="fixed">
      <parent link="${prefix}base_link"/>
      <origin xyz="0 0 ${wall_thickness}"/>
      <child link="${prefix}bottom_link"/>
    </joint>

    <link name="${prefix}bottom_link">
      <inertial>
        <mass value="10.0"/>
        <origin xyz="0 0 ${-wall_thickness/2}"/>
        <inertia ixx="1" ixy="0" ixz="0"
                 iyy="1" iyz="0" izz="1"/>
      </inertial>
      <visual>
        <origin xyz="0 0 ${-wall_thickness/2}"/>
        <geometry>
          <box size="${width - 2 * wall_thickness} ${depth - 2 * wall_thickness} ${wall_thickness}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="0 0 ${-wall_thickness/2}"/>
        <geometry>
          <box size="${width - 2 * wall_thickness} ${depth - 2 * wall_thickness} ${wall_thickness}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}wall1_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <origin xyz="${width / 2} 0 ${height / 2}"
              rpy="0 0 0"/>
      <child link="${prefix}wall1_link"/>
    </joint>
    <link name="${prefix}wall1_link">
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 ${-wall_thickness / 2}"/>
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0"
                 izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="${-wall_thickness / 2} 0 0"/>
        <geometry>
          <box size="${wall_thickness} ${depth} ${height}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="${-wall_thickness / 2}  0 0"/>
        <geometry>
          <box size="${wall_thickness} ${depth} ${height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}wall3_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <origin xyz="${-width / 2} 0 ${height / 2}"
              rpy="0 0 0"/>
      <child link="${prefix}wall3_link"/>
    </joint>
    <link name="${prefix}wall3_link">
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 ${wall_thickness / 2}"/>
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0"
                 izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="${wall_thickness / 2} 0 0"/>
        <geometry>
          <box size="${wall_thickness} ${depth} ${height}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="${wall_thickness / 2} 0 0"/>
        <geometry>
          <box size="${wall_thickness} ${depth} ${height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}wall2_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <origin xyz="0 ${depth / 2} ${height / 2}"
              rpy="0 0 0"/>
      <child link="${prefix}wall2_link"/>
    </joint>
    <link name="${prefix}wall2_link">
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 ${-wall_thickness / 2}"/>
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0"
                 izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="0 ${-wall_thickness / 2} 0"/>
        <geometry>
          <box size="${width - 2 * wall_thickness} ${wall_thickness} ${height}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="${-wall_thickness / 2}  0 0"/>
        <geometry>
          <box size="${width - 2 * wall_thickness} ${wall_thickness} ${height}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}wall4_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <origin xyz="0 ${-depth / 2} ${height / 2}"
              rpy="0 0 0"/>
      <child link="${prefix}wall4_link"/>
    </joint>
    <link name="${prefix}wall4_link">
      <inertial>
        <mass value="1.0"/>
        <origin xyz="0 0 ${wall_thickness / 2}"/>
        <inertia ixx="0.1" ixy="0" ixz="0"
                 iyy="0.1" iyz="0"
                 izz="0.01"/>
      </inertial>
      <visual>
        <origin xyz="0 ${wall_thickness / 2} 0"/>
        <geometry>
          <box size="${width - 2 * wall_thickness} ${wall_thickness} ${height}"/>
        </geometry>
        <material name="grey"/>
      </visual>
      <collision>
        <origin xyz="${wall_thickness / 2}  0 0"/>
        <geometry>
          <box size="${width - 2 * wall_thickness} ${wall_thickness} ${height}"/>
        </geometry>
      </collision>
    </link>

  </xacro:macro>
</robot>
